Fix do_transform_cloud for multi-channelled pointcloud2.
When multi-channelled pointcloud2 (e.g. index channel) is passed to
do_transform_cloud, pack_into(buff, offset, *p) returns

    error: pack_into expected 4 items for packing (got 3)

since it tries to pack only xyz data with original field list.

This commit appends auxiliary channel data to output data.